### ISSUE TITLE
 关于找不到文件  About file not found：../Unicorn_outputs/unicorn_det_convnext_tiny_800x1280/best_ckpt.pth

### ISSUE THREAD

**Issue by 972821054** [MasterBin-IIAU/Unicorn#11]
Hello, you provided a good way to solve the exhibition. When I tried to carry out multi-target tracking training, I found that the pre training weight you provided could not be obtained. Have you modified the code, or is there any way to obtain it?
![image](https://user-images.githubusercontent.com/83146207/180382094-6ad1efbf-652b-463f-8969-e8309adfc81b.png)

**Comment by MasterBin-IIAU** [comment]
@972821054 Hi, as mentioned in the [model_zoo.md](https://github.com/MasterBin-IIAU/Unicorn/blob/master/assets/model_zoo.md), please download pre-trained weights and put it under the Unicorn_outputs folder.

**Comment by 972821054** [comment]
@MasterBin-IIAU OK, thank you very much！ Another question is whether this method can be used in the data set designed by yourself. What should be paid attention to in the design process? I have made a data set about vehicle multi-target tracking, which I want to apply to your method.

**Comment by MasterBin-IIAU** [comment]
@972821054 Hi, according to the number of classes of tracked objects in your dataset, you may need to change self.num_classes in the experiment file. By default, self.num_classes=8 for BDD100K and self.num_classes=1 for MOT challenge. Then you may need to change [here](https://github.com/MasterBin-IIAU/Unicorn/blob/cafd15b9abb58297f4986775fa369abc6d1802cf/unicorn/exp/unicorn_track.py#L172) for loading the COCO-pretrained weights of classifiers. Besides, you need to write your own [mot dataset](https://github.com/MasterBin-IIAU/Unicorn/blob/cafd15b9abb58297f4986775fa369abc6d1802cf/unicorn/exp/unicorn_track.py#L301) for training on it.

**Comment by 972821054** [comment]
@MasterBin-IIAU Have you ever asked this question? I haven't solved this problem with online methods. Sorry for the inconvenience!
![image](https://user-images.githubusercontent.com/83146207/180394168-7a85f78f-cb23-461b-bb1c-d6e036d104ca.png)
![image](https://user-images.githubusercontent.com/83146207/180394220-c3c445f9-37ca-43e2-8d28-627fdec5ce9f.png)

**Comment by MasterBin-IIAU** [comment]
@972821054 It seems the version of mmcv is not compatible with that of your cuda. Please refer to the official website of mmcv for a compatible version.

**Comment by 972821054** [comment]
@MasterBin-IIAU thank you very much！I still keep reporting errors. I'll try reinstalling virtual mirage. Thank you again.

**Comment by 972821054** [comment]
@MasterBin-IIAU 您好，请问您的python版本是3.7吗？我运行的时候报错，需要使用3.8的版本。
![image](https://user-images.githubusercontent.com/83146207/180419212-830fd913-1b88-4961-8276-69e1a0574d46.png)
The code I run is:
![image](https://user-images.githubusercontent.com/83146207/180419419-93edcaa3-e465-4eba-a2f4-e0b411c09a8a.png)

**Comment by 972821054** [comment]
@MasterBin-IIAU Hello, is your Python version 3.7? When I run, I report an error and need to use version 3.8. 
![image](https://user-images.githubusercontent.com/83146207/180419608-bd99309a-3b5a-458f-9dd3-144d9a7fb66f.png)

The code I run is:
![image](https://user-images.githubusercontent.com/83146207/180419715-186d6f06-35eb-4322-845a-957d2713aa21.png)

**Comment by MasterBin-IIAU** [comment]
@972821054 Yes, we use python 3.7

**Comment by 972821054** [comment]
@MasterBin-IIAU Can you share your bdd100k file? I want to operate you directly and try it successfully. If you are willing to share, I will be very grateful!

**Comment by 972821054** [comment]
@MasterBin-IIAU Hello, if I want to do mot training, which pre training weight do I need? Can my {exp_name} be directly set as the example you give?
![image](https://user-images.githubusercontent.com/83146207/180429544-ee441313-9285-4a9d-989c-458c16b547bd.png)

**Comment by MasterBin-IIAU** [comment]
@972821054 if you want to train unicorn with convnext-tiny backbone for object tracking, use pretrained weights of [unicorn_det_convnext_tiny_800x1280](https://drive.google.com/file/d/11kLsIOp6jQEEM0ZmOvvsJW_RgjgCxuYZ/view?usp=sharing)

**Comment by 972821054** [comment]
@MasterBin-IIAU Thank you for your valuable suggestions. I have three questions to ask you.

First: for motchallenge type training set (the organization is similar to mot16), but there is no thing det.txt(There is a det folder in the directory. There is a det.txt file in the folder, but the file has no content) in my data set . In this case, can I use the file convert_mot17_to_coco provided by you to Generate json file?

Second: if I use single classification here, does it need to be adjusted? In the case of single classification multi-target tracking, Do self.num_ classes need no adjustment?
![e7bf2fc2137c44b20f06f2fb98e504c](https://user-images.githubusercontent.com/83146207/180477053-c409a61a-caf9-4fe4-bab4-d2c67375326d.png)

The third one: whether the data set is put correctly here, and in the last line of comment, for omni_dataset_mot is correct?
![7db4c4bcf233bbb897ff47feed1d70f](https://user-images.githubusercontent.com/83146207/180477171-5e0f62c3-2e3f-4970-9569-66d9ccea4c18.png)

Thank you again for your valuable comments！

**Comment by 972821054** [comment]
@MasterBin-IIAU Hello, if I want to use Unicorn_ track_ tiny_ mot_ Only, which configurations and parameters need to be changed?And if the test is carried out, which parameters need to be modified?
![image](https://user-images.githubusercontent.com/83146207/180585239-77fb5e22-3e83-44d8-862e-aac0f967e0f5.png)
![image](https://user-images.githubusercontent.com/83146207/180585261-ce176a64-8f9a-410e-9e14-4fff1e91cdcd.png)

**Comment by MasterBin-IIAU** [comment]
> @MasterBin-IIAU Thank you for your valuable suggestions. I have three questions to ask you.
> 
> First: for motchallenge type training set (the organization is similar to mot16), but there is no thing det.txt(There is a det folder in the directory. There is a det.txt file in the folder, but the file has no content) in my data set . In this case, can I use the file convert_mot17_to_coco provided by you to Generate json file?
> 
> Second: if I use single classification here, does it need to be adjusted? In the case of single classification multi-target tracking, Do self.num_ classes need no adjustment? ![e7bf2fc2137c44b20f06f2fb98e504c](https://user-images.githubusercontent.com/83146207/180477053-c409a61a-caf9-4fe4-bab4-d2c67375326d.png)
> 
> The third one: whether the data set is put correctly here, and in the last line of comment, for omni_dataset_mot is correct? ![7db4c4bcf233bbb897ff47feed1d70f](https://user-images.githubusercontent.com/83146207/180477171-5e0f62c3-2e3f-4970-9569-66d9ccea4c18.png)
> 
> Thank you again for your valuable comments！

Answer to question 1: Yes, we do not need det.txt and only need gt.txt
Answer to question 2: self.num_ classes should be equal to the number of classes of your mot dataset.
Answer to question 3: Yes. That is right.

**Comment by 972821054** [comment]
@MasterBin-IIAU Hello, if I want to use Unicorn_ track_ tiny_ mot_ Only, which configurations and parameters need to be changed?And if the test is carried out, which parameters need to be modified?
![image](https://user-images.githubusercontent.com/83146207/180647892-7f47cdfb-c3c7-4720-a832-66a34c672672.png)
![image](https://user-images.githubusercontent.com/83146207/180647894-8acd8e59-e727-4a6f-8521-b1824979d542.png)

**Comment by 972821054** [comment]
@MasterBin-IIAU Hello, I modified the pre training weight according to what you said. My classification number is 1, but why do I still report an error? The error is as follows.
![e4fb0f20cb52adff7fc744cf940b280](https://user-images.githubusercontent.com/83146207/180649698-ece9e263-6ef5-4ffd-977c-2e0e324df029.png)
![image](https://user-images.githubusercontent.com/83146207/180649709-6d080136-30b1-419a-bfdb-6159f44c8e04.png)

**Comment by MasterBin-IIAU** [comment]
@972821054 There is no need to modify pre-trained weights. If there is only one class for your own dataset, please set self.num_classes to 1.

**Comment by 972821054** [comment]
@MasterBin-IIAU Thank you for sharing! Have you tried to use your algorithm (or bytetrack algorithm) in vehicle training? After my training, the detection result is very unsatisfactory.

**Comment by MasterBin-IIAU** [comment]
@972821054 Hi, we also trained and tested our method on the BDD100K dataset, a large-scale MOT benchmark on autonomous driving. The dataset contains 8 classes (pedestrian, rider, car, truck, bus, train, motorcycle, bicycle). Unicorn also achieves good performance on this dataset.

**Comment by 972821054** [comment]
@MasterBin-IIAU Did you modify any parameters?and what is your Mota value? thanks

**Comment by MasterBin-IIAU** [comment]
The result is shown [here](https://github.com/MasterBin-IIAU/Unicorn/blob/master/assets/MOT-BDD.png). The corresponding experiment and trained model are [unicorn_track_large.py](https://github.com/MasterBin-IIAU/Unicorn/blob/master/exps/default/unicorn_track_large.py) and [latest_ckpt.pth](https://drive.google.com/file/d/1P4__Xd1wvET5Sow21_zmOx3lupAuEWN6/view) respectively.

**Comment by 972821054** [comment]
@MasterBin-IIAU 
![image](https://user-images.githubusercontent.com/83146207/181867668-053abaa0-44bc-43a8-83e6-dd254c9aaee8.png)
Hello, may I ask you to modify num_ Classes is 1, does it mean here? After I modify it, the above mismatch error will appear.

**Comment by 972821054** [comment]
@ @MasterBin-IIAU hello if i want to save the video of track，what need ido？
