### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'new'

### ISSUE THREAD

**Issue by changseob1001** [MasterBin-IIAU/Unicorn#12]
i run to demo but have some error

box_corner = prediction.new(prediction.shape)
AttributeError: 'tuple' object has no attribute 'new'

what is this error?

**Comment by MasterBin-IIAU** [comment]
@changsub132 Please provide more details about your code.

**Comment by changseob1001** [comment]
i run demo.py that "python tools/demo.py video --path ./3.mp4 -f exps/default/unicorn_track_large_mot_challenge_mask.py --save_result"

and i change the demo.py
parser.add_argument("-c", "--ckpt", default="Unicorn_outputs/unicorn_track_large_mot_challenge_mask/latest_ckpt.pth", type=str, help="ckpt for eval")
and
parser.add_argument(
        "--device",
        default="gpu",
        type=str,
        help="device to run our model, can either be cpu or gpu",
    )

**Comment by changseob1001** [comment]
and i think code line from 163 to 166 "inconsistent use of tabs and spaces in indentation" error

try:
	outputs = self.model(img)
except:
	outputs, seq_dict = self.model(img)

**Comment by changseob1001** [comment]
but i dont know "AttributeError: 'tuple' object has no attribute 'new'" this error

**Comment by MasterBin-IIAU** [comment]
@changsub132 This demo.py is only used for object detection and instance segmentation. Please pick a file from the followings: [unicorn_det_r50_800x1280.py](https://github.com/MasterBin-IIAU/Unicorn/blob/master/exps/default/unicorn_det_r50_800x1280.py), [unicorn_det_convnext_tiny_800x1280.py](https://github.com/MasterBin-IIAU/Unicorn/blob/master/exps/default/unicorn_det_convnext_tiny_800x1280.py), [unicorn_det_convnext_large_800x1280.py](https://github.com/MasterBin-IIAU/Unicorn/blob/master/exps/default/unicorn_det_convnext_large_800x1280.py), [unicorn_inst_convnext_tiny_800x1280.py](https://github.com/MasterBin-IIAU/Unicorn/blob/master/exps/default/unicorn_inst_convnext_tiny_800x1280.py)
