### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by TIYASARIT** [MasterBin-IIAU/Unicorn#14]
![q1](https://user-images.githubusercontent.com/46254035/180677444-ac8b94e9-6843-42d3-9548-ccade1530460.png)
I am going through the installation step, can't understand the following error. Can anyone help me to resolve this.

**Comment by MasterBin-IIAU** [comment]
@TIYASARIT Hi, it seems that you have not installed git on your system. Besides, we do not suggest running this project on the Windows system. Please use Linux system like Ubuntu instead.

**Comment by TIYASARIT** [comment]
@MasterBin-IIAU  Thanks, I do have Git installed.... Is there any path dependency?

I will try to switch to Ubuntu. Tell me one thing, do I need GPU along with Ubuntu to execute this?
