### ISSUE TITLE
CPU-mode not supported?

### ISSUE THREAD

**Issue by carsten12** [MasterBin-IIAU/Unicorn#25]
Under the assumption that I can try out Unicorn with some pre-trained models, I tried to install it on a Mac and a PC, both w/o nVidia GPU. In step 3 when executing bash make.sh, setup.py is called which is testing for torch.cuda.is_available() and is raising an exception if the function returns false. So running in CPU-mode is not foreseen?

**Comment by MasterBin-IIAU** [comment]
Hi, Unicorn uses [Deformable Attention](https://github.com/fundamentalvision/Deformable-DETR) for feature interaction. Unfortunately, this operation is not supported to run on the CPU for now.
