### ISSUE TITLE
why Train dataset  include detection dataset ?

### ISSUE THREAD

**Issue by CarlHuangNuc** [MasterBin-IIAU/Unicorn#26]
Hi ,
     
  Why train tracking step1 ,need BDD detection dataset?

![image](https://user-images.githubusercontent.com/104048874/186290289-1beb17bd-4895-4a8e-951e-17c073cc9ec6.png)

**Comment by MasterBin-IIAU** [comment]
@CarlHuangNuc Hi, since Unicorn takes two frames (reference frame and current frame) as the inputs, detection datasets are used to simulate frames sampled from videos.
