### ISSUE TITLE
mmtracking framework support ?

### ISSUE THREAD

**Issue by CarlHuangNuc** [MasterBin-IIAU/Unicorn#27]
Hi,

This is a very awesome work. I want to integrate it into mmtracking framework.
Do you agree it?  I want to refactor code and Pull requests to mmtracking git .

**Comment by MasterBin-IIAU** [comment]
@CarlHuangNuc Hi, thanks for your appreciation of our work. 
Of course, it is also my pleasure to see Unicorn integrated to the mmtracking repo :)
