### ISSUE TITLE
The number of classes in the detection loss.

### ISSUE THREAD

**Issue by JingweiZhang12** [MasterBin-IIAU/Unicorn#3]
Wonderful work! As stated in the paper, the model is trained under the supervision of corresponding loss and detection loss using the data from SOT and MOT. 
For the part of classification loss in detection,  I want to know how to handle the instances from SOT datasets whose classes are outside MOT datasets. Also, do you think the SOT performance of this model is related to whether the tracked object class is in the MOT dataset?

**Comment by MasterBin-IIAU** [comment]
@JingweiZhang12 Hi, thanks for your appreciation of our work.
SOT and MOT care about different types of instances. Specifically, SOT needs to track objects of **any class** given in the first frame. But MOT tracks objects of **specific classes** (person, car, etc). To deal with this problem, at the end of the unified head, Unicorn uses two different classifiers for [SOT](https://github.com/MasterBin-IIAU/Unicorn/blob/436f1d2643e9b01f2bc475ef1f01107ff242c74d/unicorn/models/unicorn_head.py#L161) and [MOT](https://github.com/MasterBin-IIAU/Unicorn/blob/436f1d2643e9b01f2bc475ef1f01107ff242c74d/unicorn/models/unicorn_head.py#L152). Thus in this way, the performance of SOT would not be affected by the classes of MOT.

**Comment by JingweiZhang12** [comment]
Thanks for your reply. Looking forward to your supplement materials about the more detatils of this method.

**Comment by MasterBin-IIAU** [comment]
@JingweiZhang12 We will release an updated arxiv paper in recent days. The supplementary materials will be released together :)

**Comment by MasterBin-IIAU** [comment]
@JingweiZhang12 Hi, the updated paper with supplementary materials is now available on arxiv now :)
