### ISSUE TITLE
Checkpoint for mot17 is missing

### ISSUE THREAD

**Issue by harkiratbehl** [MasterBin-IIAU/Unicorn#33]
Hi Authors,

Thanks and congratulations on the wonderful work. I wonder if you can please share the checkpoint for the second group of models unicorn_track_large_mot_challenge_mask. The link is missing from the readme and from Huggingface https://huggingface.co/NimaBoscarino/unicorn_track_large_mot_challenge_mask/tree/main 

Regards
Harkirat

**Comment by harkiratbehl** [comment]
Is there any checkpoint available for mot17?

**Comment by Biexf** [comment]
I can't find the model either

**Comment by MasterBin-IIAU** [comment]
@harkiratbehl @Biexf Hi, the link of unicorn_track_large_mot_challenge_mask has been fixed. Please retry it :)
