### ISSUE TITLE
我在进行复现时找不到unicorn_track_tiny_vos_only的latest_ckpt.pth

### ISSUE THREAD

**Issue by haimeilv** [MasterBin-IIAU/Unicorn#34]
如题，我点击您给的连接后一直显示失败，请问您可以发送模型到lvhaimei666@163.com吗？如果不方便的话请问是否可以提供其他地址？万分感谢！

**Comment by MasterBin-IIAU** [comment]
@haimeilv Hi, model weights and training logs of unicorn_track_tiny_vos_only has been sent to your email. Please check it.
