### ISSUE TITLE
Question regarding input tensor preprocessing

### ISSUE THREAD

**Issue by jinuhwang** [MasterBin-IIAU/Unicorn#42]
Hi,

While following along the `inference.py` code to see how the model is working, I noticed something in the preprocessing code.

`PreprocessorX` at `external/lib/test/tracker/unicorn_sot.py:111` turns RGB format back to BGR format and the normalization process is missing. The `self.normalize` is not referenced at all as well. So the input seems to be raw image in BGR format with values between range [0, 255].

I wasn't able to find any code that performs normalization in the `forward` functions of the inner models as well.
Is it just that the model was trained on raw pixel values or am I missing anything?

**Comment by MasterBin-IIAU** [comment]
Hi, yes, the model takes the original pixel values ranging from 0 to 255 as the inputs. This is aligned with YOLOX, which does not use any normalization.

**Comment by jinuhwang** [comment]
@MasterBin-IIAU Thank you for the clarification, I really appreciate it.
