### ISSUE TITLE
What is the experimental setting in the paper?

### ISSUE THREAD

**Issue by fake-warrior8** [MasterBin-IIAU/Unicorn#44]
Hi, in Sec 4.1, the paper said that Unicorn in four tasks uses the same model parameters, does this mean that the Unicorn model is trained in a multi task manner? Meanwhile, I found that in the ablation study in Sec 4.6, the four results of  Unification in the Single task part of Table 7 are different from  the results in Tables 1, 3, 4, 6, what is the difference between the Unification setting in Table 7 and those in Table 1,3, 4, 6?

**Comment by MasterBin-IIAU** [comment]
Hi, yes, Unicorn is jointly trained on datasets from four tasks and there is only one set of parameters across four tasks.
Table 1, 3, 4, 6 use ConvNeXt-Large as the backbone. While we use ConvNeXt-Tiny as the backbone for ablations.

**Comment by fake-warrior8** [comment]
> Hi, yes, Unicorn is jointly trained on datasets from four tasks and there is only one set of parameters across four tasks. Table 1, 3, 4, 6 use ConvNeXt-Large as the backbone. While we use ConvNeXt-Tiny as the backbone for ablations.

Thank you for your reply.
