### ISSUE TITLE
Using custom Yolo model and video inference

### ISSUE THREAD

**Issue by bdubbs09** [MasterBin-IIAU/Unicorn#5]
- Is there a way to upload a custom trained model then use it to track and perform inference in a custom video?
- Does Unicorn only accept YoloX, or would it be able to accept a generic (ex Yolo5/6/7) trained model?

This may be addressed somewhere in the code, but I have not found it yet. Any help would be amazing!

**Comment by MasterBin-IIAU** [comment]
@bdubbs09 Hi, Thanks for your attention.
- Users can use Unicorn to track objects in a custom video. We will provide an example later.
- For now, Unicorn is tightly coupled with the codebase of YOLOX. But it certainly can work with other detectors like YOLOv5-v7.

**Comment by bdubbs09** [comment]
Thanks for addressing!

- Do you have any suggestions for an integration point for a different Yolo model? Or at least where to start to build that additional functionality? I don't mind making a PR for a feature, but if you'd rather it be done a specific way, no worries.

Thanks again for the help!

**Comment by MasterBin-IIAU** [comment]
@bdubbs09 Hi, in my opinion, we need to first reimplement [YOLOv5](https://github.com/ultralytics/yolov5), [YOLOX](https://github.com/Megvii-BaseDetection/YOLOX), and [YOLOV7](https://github.com/WongKinYiu/yolov7) with a unified codebase, if we want to seamlessly switch between them. This may require a very large effort and we may not have enough energy to do this for now. But we highly admire and welcome related PR :)
